#spring:
#  application:
#    name: coupon-Eureka
#server:
#  port: 8080
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    #表示是否从eureka server中获取注册信息，默认是true，如果是一个单节点的Eureka Server则设置为false
#    fetch-registry: false
#    #是否将自己注册到Eureka Server中，默认是true，因目前是单节点的Eureka Server ，设置为false
#    register-with-eureka: false
#    #设置Eureka Server所在的地址，查询和注册服务都需要依赖此地址
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/